apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      serviceAccountName: mdaw
      initContainers:
        - name: init-auth
          image: busybox:1.28
          command: ["sh", "-c", "sleep 2"] # Wait for redis to be ready
      containers:
        - name: payment
          image: ponytojas/practica_mdaw_payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5570
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth:5554
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5570"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: STORE_SERVICE_URL
              value: http://store:5551
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
