apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-v1
  labels:
    app: core
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
      version: v1
  template:
    metadata:
      labels:
        app: core
        version: v1
    spec:
      serviceAccountName: mdaw
      containers:
        - name: core
          image: ponytojas/practica_mdaw_core_node:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5550
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth:5554
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5550"
            - name: STORE_SERVICE_URL
              value: http://store:5551
