apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: ponytojas/practica_mdaw_store:latest
          env:
            - name: DB_SERVICE_URL
              value: "http://db:5555"
            - name: HTTP_PORT
              value: "5551"
            - name: DEBUG
              value: "false"
