apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ponytojas/practica_mdaw_payment:latest
          env:
            - name: HTTP_PORT
              value: "5570"
            - name: AUTH_SERVICE_URL
              value: "http://auth:5554"
            - name: STORE_SERVICE_URL
              value: "http://store:5551"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: DEBUG
              value: "false"
