---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - name: "5554"
      port: 5554
      targetPort: 5554

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  ports:
    - name: "5560"
      port: 5560
      targetPort: 5560

---
apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  ports:
    - name: "5550"
      port: 5550
      targetPort: 5550

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
    - name: "5570"
      port: 5570
      targetPort: 5570

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  ports:
    - name: "5551"
      port: 5551
      targetPort: 5551

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ponytojas/practica_mdaw_auth_node:latest
          ports:
            - containerPort: 5554
              protocol: TCP
          env:
            - name: DB_SERVICE_URL
              value: http://db:5555
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5554"
            - name: JWT_SECRET
              value: JunoMolaAsiQueMasPlachanito
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth:5554
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5560"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: STORE_SERVICE_URL
              value: http://store:5551
          image: ponytojas/practica_mdaw_cart_node:latest
          name: cart
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5560
              hostPort: 5560
              protocol: TCP
      hostname: cart
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth:5554
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5550"
            - name: STORE_SERVICE_URL
              value: http://store:5551
          image: ponytojas/practica_mdaw_core_node:latest
          name: core
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5550
              hostPort: 5550
              protocol: TCP
      hostname: core
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: postgres
            - name: DB_PASS
              value: mysecretpassword
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: disable
            - name: DB_USER
              value: postgres
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5555"
          image: ponytojas/practica_mdaw_database_node:latest
          name: db
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5555
              hostPort: 5555
              protocol: TCP
      hostname: db
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: VITE_CART_BASE
              value: https://nginx/cart
            - name: VITE_CORE_BASE
              value: https://nginx/api
            - name: VITE_PAYMENT_BASE
              value: https://nginx/payment
          image: ponytojas/practica_mdaw_frontend:latest
          name: frontend
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              hostPort: 8800
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: ponytojas/practica_mdaw_nginx:latest
          securityContext:
            allowPrivilegeEscalation: false
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 443
              hostPort: 8443
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth:5554
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5570"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: STORE_SERVICE_URL
              value: http://store:5551
          image: ponytojas/practica_mdaw_payment_node:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          name: payment
          ports:
            - containerPort: 5570
              hostPort: 5570
              protocol: TCP
      hostname: payment
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      containers:
        - name: postgres
          image: ponytojas/practica_mdaw_postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: postgres
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4-alpine3.19
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: ponytojas/practica_mdaw_store_node:latest
          ports:
            - containerPort: 5551
              protocol: TCP
          env:
            - name: DB_SERVICE_URL
              value: http://db:5555
            - name: DEBUG
              value: "false"
            - name: HTTP_PORT
              value: "5551"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
