version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
