version: "3.7"
services:
  traefik:
    image: traefik:v2.10.7
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "4444:80"
      - "8080:8080"
    environment:
      - "LOG_LEVEL=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    logging:
      options:
        max-size: 50m

  postgres:
    image: ponytojas/practica_mdaw_postgres:0.0.2
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    hostname: redis
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal

  db:
    hostname: db
    image: ponytojas/practica_mdaw_database:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - HTTP_PORT=5555
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - postgres
      - redis

  auth:
    hostname: auth
    image: ponytojas/practica_mdaw_auth:latest
    environment:
      - DB_SERVICE_URL=http://db:5555
      - REDIS_HOST=redis
      - JWT_SECRET=JunoMolaAsiQueMasPlachanito
      - HTTP_PORT=5554
      - REDIS_PORT=6379
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  store:
    hostname: store
    image: ponytojas/practica_mdaw_store:latest
    environment:
      - DB_SERVICE_URL=http://db:5555
      - HTTP_PORT=5551
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  cart:
    hostname: cart
    image: ponytojas/practica_mdaw_cart:latest
    environment:
      - HTTP_PORT=5560
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.cart.rule=PathPrefix(`/cart`)"
      - "traefik.http.routers.cart.entrypoints=web"
      - "traefik.http.services.cart.loadbalancer.server.port=5560"
      - "traefik.http.middlewares.cart-stripprefix.stripprefix.prefixes=/cart"
      - "traefik.http.routers.cart.middlewares=cart-stripprefix"
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  payment:
    hostname: payment
    image: ponytojas/practica_mdaw_payment:latest
    environment:
      - HTTP_PORT=5570
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.routers.payment.entrypoints=web"
      - "traefik.http.services.payment.loadbalancer.server.port=5570"
      - "traefik.http.middlewares.payment-stripprefix.stripprefix.prefixes=/payment"
      - "traefik.http.routers.payment.middlewares=payment-stripprefix"
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  core:
    hostname: core
    image: ponytojas/practica_mdaw_core:latest
    environment:
      - HTTP_PORT=5550
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - DEBUG=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.core.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.core.entrypoints=web"
      - "traefik.http.services.core.loadbalancer.server.port=5550"
      - "traefik.http.middlewares.core-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.core.middlewares=core-stripprefix"
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres
      - auth
      - store
      - traefik

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "222:22"

volumes:
  portainer_data:
  gitea_data:
  postgres_data:

networks:
  internal:
    driver: bridge
