version: "3.7"
services:
  nginx:
      image: ponytojas/practica_mdaw_nginx:latest
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - postgres
        - redis
        - db
        - auth
        - store
        - cart
        - payment
        - core
        - frontend
      networks:
        - internal

  postgres:
    image: ponytojas/practica_mdaw_postgres:latest
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    hostname: redis
    image: redis:7.2.4-alpine3.19
    restart: always
    networks:
      - internal

  db:
    hostname: db
    image: ponytojas/practica_mdaw_database_node:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - HTTP_PORT=5555
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - postgres
      - redis

  auth:
    hostname: auth
    image: ponytojas/practica_mdaw_auth_node:latest
    environment:
      - DB_SERVICE_URL=http://db:5555
      - REDIS_HOST=redis
      - JWT_SECRET=JunoMolaAsiQueMasPlachanito
      - HTTP_PORT=5554
      - REDIS_PORT=6379
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  store:
    hostname: store
    image: ponytojas/practica_mdaw_store_node:latest
    environment:
      - DB_SERVICE_URL=http://db:5555
      - HTTP_PORT=5551
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  cart:
    hostname: cart
    image: ponytojas/practica_mdaw_cart_node:latest
    environment:
      - HTTP_PORT=5560
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  payment:
    hostname: payment
    image: ponytojas/practica_mdaw_payment_node:latest
    environment:
      - HTTP_PORT=5570
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres

  core:
    hostname: core
    image: ponytojas/practica_mdaw_core_node:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - HTTP_PORT=5550
      - AUTH_SERVICE_URL=http://auth:5554
      - STORE_SERVICE_URL=http://store:5551
      - DEBUG=false
    networks:
      - internal
    depends_on:
      - db
      - redis
      - postgres
      - auth
      - store

  frontend:
    image: ponytojas/practica_mdaw_frontend:latest
    environment:
      - VITE_CORE_BASE=https://localhost/api
      - VITE_CART_BASE=https://localhost/cart
      - VITE_PAYMENT_BASE=https://localhost/payment
    depends_on:
      - core
    networks:
      - internal

volumes:
  postgres_data:


networks:
  internal:
    driver: bridge
